config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  get '/admins' => 'admins#index'
  get '/job/:id/count' => 'jobs#queryCount'
  post '/job/:id/run' => 'jobs#run'
  get '/download/:sub_job_id/:file_type', to: 'downloads#secureGet', as: 'secure_get'
  get '/visualizations/', to: 'visualizations#index', as: 'visualizations'
  post '/query/', to: 'visualizations#query', as: 'query'

  get '/feeds/actions/:id', to: 'feeds#actions', as: 'action_feed'

  root 'home#index'
  resources :jobs
  resources :object_rules do
    resources :field_rules
  end


  #DELAYEDJOBWEB
  authenticated :admin do
    mount DelayedJobWeb, :at => "/delayed_job"
  end
  #RAILS ADMIN
  mount RailsAdmin::Engine => '/admin/', as: 'rails_admin'

end

app/models/field_rule.rb
class FieldRule < ActiveRecord::Base
	belongs_to :object_rule
end

app/controllers/field_rules_controller.rb
class 
  FieldRulesController < ApplicationController
  before_action :set_field_rule, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /field_rules
  # GET /field_rules.json
  def index
    @object_rule = ObjectRule.find(params[:object_rule_id])
    @field_rules = FieldRule.where(object_rule_id: params[:object_rule_id])

    salesforce = Restforce.new
    actionkit = ActionKitApi.new
    
    @actionKitFields = []
    @salesForceFields = []
    actionkit.query("SELECT DISTINCT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = '#{@object_rule.extract_object}'").each do |field|
      @actionKitFields.push(field[0])
    end
    salesforce.describe(@object_rule.load_object)[:fields].each do |field|
      @salesForceFields.push(field[:name])
    end
    gon.push(:actionKitFields => @actionKitFields,
             :salesForceFields => @salesForceFields)
  end

  # GET /field_rules/1
  # GET /field_rules/1.json
  def show
    @field_rule = FieldRule.find(params[:id])
    @object_rule = ObjectRule.find(params[:object_rule_id])
  end

  # GET /field_rules/new
  def new
    @field_rule = FieldRule.new
    @object_rule = ObjectRule.find(params[:object_rule_id])
  end

  # GET /field_rules/1/edit
  def edit
    @field_rule = FieldRule.find(params[:id])
    @object_rule = ObjectRule.find(params[:object_rule_id])
  end

  # POST /field_rules
  # POST /field_rules.json
  def create
    @field_rule = FieldRule.new(field_rule_params)
    @field_rule.object_rule_id = params[:object_rule_id]

    respond_to do |format|
      if @field_rule.save
        format.html { redirect_to object_rule_path(@field_rule.object_rule.id), notice: ' field rule was successfully created.' }
        format.json { render :show, status: :created, location: @field_rule }
      else
        format.html { render :new }
        format.json { render json: @field_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /field_rules/1
  # PATCH/PUT /field_rules/1.json
  def update
    respond_to do |format|
      if @field_rule.update(field_rule_params)
        format.html { redirect_to object_rule_field_rule_url, notice: ' field rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @field_rule }
      else
        format.html { render :edit }
        format.json { render json: @field_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /field_rules/1
  # DELETE /field_rules/1.json
  def destroy
    @field_rule.destroy
    respond_to do |format|
      format.html { redirect_to object_rule_field_rules_url, notice: ' field rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field_rule
      @field_rule = FieldRule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_rule_params
      params.require(:field_rule).permit(:extract_field, :transformation, :load_field, :active, :is_primary, :is_foreign_key)
    end
end

app/views/field_rules/_form.html.erb
<%= form_for([@object_rule, @field_rule]) do |f| %>
  <% if @field_rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@field_rule.errors.count, "error") %> prohibited this field_rule from being saved:</h2>
      <ul>
      <% @field_rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :extract_field %>
    <%= f.text_field :extract_field %>
  </div>
  <div class="field">
    <%= f.label :transformation %>
    <%= f.text_area :transformation %>
  </div>
  <div class="field">
    <%= f.label :load_field %>
    <%= f.text_field :load_field %>
  </div>
  <div class="field">
    <label for="field_rule[active]"><%= f.check_box :active %>&nbsp;Active</label>
  </div>
  <div class="field">
    <label for="field_rule[is_primary]"><%= f.check_box :is_primary %>&nbsp;Primary</label>
  </div>
  <div class="field">
    <label for="field_rule[is_foreign_key]"><%= f.check_box :is_foreign_key %>&nbsp;Foreign Key</label>
  </div>
  <div class="actions">
    <%= f.submit "Save", class: "button radius" %>
  </div>
<% end %>

app/views/field_rules/edit.html.erb
<div class="row">
	<div class="small-12 medium-6 columns">
		<div class="pan">
			<h3>Edit Field Rule</h3>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/field_rules/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <div class="pan">
      <h3><%= @object_rule.extract_object %> to <%= @object_rule.load_object %><%= link_to 'New Etl field rule', new_object_rule_field_rule_path, class: 'right button inline radius' %></h3>
      <table>
        <thead>
          <tr>
            <th width="200">Extract field</th>
            <th width="200">Transformation</th>
            <th width="200">Load field</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @field_rules.each do |field_rule| %>
            <tr>
              <td width="200"><%= field_rule.extract_field %></td>
              <td width="200"><%= field_rule.transformation %></td>
              <td width="200"><%= field_rule.load_field %></td>
              <td width="50"><%= link_to "Edit", edit_object_rule_field_rule_path(@object_rule, field_rule) %></td>
              <td width="50"><%= link_to "Delete", object_rule_field_rule_path(@object_rule, field_rule),
            :confirm => 'Are you sure?', :method => :delete %></td>
            </tr>
          <% end %>
            <%= form_tag("/object_rules/#{@object_rule.id}/field_rules", method:"POST") do %>
              <tr>
                <td width="200"><input id="field_rule_extract_field" class="radius" type="text" name="field_rule[extract_field]" /></td>
                <td width="200"><input id="field_rule_transformation" class="radius" type="text" name="field_rule[transformation]" /></td>
                <td width="200"><input id="field_rule_load_field" class="radius" type="text" name="field_rule[load_field]" /></td>
              </tr>
              <tr>
                <td class="text-right" colspan="3"><button type="submit" class="button radius">Save</button></td>
              </tr>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div class="bank row">
        <div class="small-12 medium-6 columns">
          <% @actionKitFields.each do |field| %>
          <span class="ak-label">
            <%= field %>
          </span>
          <% end %>
        </div>
        <div class="small-12 medium-6 columns">
          <% @salesForceFields.each do |field| %>
          <span class="sf-label">
            <%= field %>
          </span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">

  var substringMatcher = function(strs) {
    return function findMatches(q, cb) {
      var matches, substrRegex;
   
      // an array that will be populated with substring matches
      matches = [];
   
      // regex used to determine if a string contains the substring `q`
      substrRegex = new RegExp(q, 'i');
   
      // iterate through the pool of strings and for any string that
      // contains the substring `q`, add it to the `matches` array
      $.each(strs, function(i, str) {
        if (substrRegex.test(str)) {
          // the typeahead jQuery plugin expects suggestions to a
          // JavaScript object, refer to typeahead docs for more info
          matches.push({ value: str });
        }
      });
   
      cb(matches);
    };
  };


  $('#field_rule_extract_field').typeahead({
    hint: true,
    highlight: true,
    minLength: 1
  },
  {
    name: 'ActionKitFields',
    displayKey: 'value',
    source: substringMatcher(gon.actionKitFields)
  });
  $('#field_rule_load_field').typeahead({
    hint: true,
    highlight: true,
    minLength: 1
  },
  {
    name: 'SalesForceFields',
    displayKey: 'value',
    source: substringMatcher(gon.salesForceFields)
  });
</script>

app/views/field_rules/new.html.erb
<div class="row">
	<div class="small-12 medium-6 columns">
		<div class="pan">
			<h3>New Field Rule</h3>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/field_rules/show.html.erb
<p>
  <strong>Extract field:</strong>
  <%= @field_rule.extract_field %>
</p>

<p>
  <strong>Transformation:</strong>
  <%= @field_rule.transformation %>
</p>

<p>
  <strong>Load field:</strong>
  <%= @field_rule.load_field %>
</p>

<p>
  <strong>Active:</strong>
  <%= @field_rule.active %>
</p>
<p>
  <strong>Is Primary:</strong>
  <%= @field_rule.is_primary %>
</p>

<%= link_to 'Edit', edit_object_rule_field_rule_path(@object_rule, @field_rule) %> |
<%= link_to 'Back', object_rule_field_rules_path %>