config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  get '/admins' => 'admins#index'
  get '/job/:id/count' => 'jobs#queryCount'
  post '/job/:id/run' => 'jobs#run'
  get '/download/:sub_job_id/:file_type', to: 'downloads#secureGet', as: 'secure_get'
  get '/visualizations/', to: 'visualizations#index', as: 'visualizations'
  post '/query/', to: 'visualizations#query', as: 'query'

  get '/feeds/actions/:id', to: 'feeds#actions', as: 'action_feed'

  root 'home#index'
  resources :jobs
  resources :object_rules do
    resources :field_rules
  end


  #DELAYEDJOBWEB
  authenticated :admin do
    mount DelayedJobWeb, :at => "/delayed_job"
  end
  #RAILS ADMIN
  mount RailsAdmin::Engine => '/admin/', as: 'rails_admin'

end

app/models/job.rb
class Job < ActiveRecord::Base
	
	has_many :sub_job_groups
	has_many :sub_jobs, through: :sub_job_groups
	has_many :job_object_rels
	has_many :object_rules, through: :job_object_rels
	
	def run
		require 'action_kit_api'
		startTime = Time.now
		logger.info "Starting job #{self.id}"
		p_object_rule = object_rules.where(is_primary: true)[0]
		job_group = SubJobGroup.create(job_id: self.id, status: 'inprogress')
		p_sub_job = SubJob.new(sub_job_group_id: job_group.id, object_rule_id: p_object_rule.id, query: self.query)
		#primary sub jobs return WHERE queries with which to run the rest of the subjobs
		new_where = p_sub_job.run
		#run all non-primaries using the results from the primary. Makes sense to me, we'll see if it holds up
		unless(new_where.empty?)
			object_rules.where(is_primary: false).each do |object_rule|
				SubJob.new(sub_job_group_id: job_group.id, object_rule_id: object_rule.id, query: "WHERE #{object_rule.field_rules.where(is_foreign_key: true)[0].extract_field} IN (#{new_where.join(', ')})").run
			end
		end
	end
	handle_asynchronously :run
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])
    @object_rules = @job.object_rules
    @sub_job_groups = @job.sub_job_groups
  end

  # GET /jobs/new
  def new
    @job = Job.new
    @object_rules = ObjectRule.all
  end

  # GET /jobs/1/edit
  def edit
    @object_rules = ObjectRule.all
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: ' job was successfully created. Thanks Obama!' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: ' job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: ' job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def queryCount
    require 'action_kit_api'
    @job = Job.find(params[:id])
    actionKit = ActionKitApi.new
    count = actionKit.findUsersCountWhere(@job.query, nil).body.gsub('[', '').gsub(']', '')
    respond_to do |format|
      format.html {render plain: count} # You probably have something like this already
      format.js {render js: 'alert("Your query will return ' + count.to_s + ' ActionKit ' + 'user'.pluralize(count.to_i) + '");'} # Add this line
    end
  end

  def run
    @job = Job.find(params[:id])
    @job.run
    redirect_to @job, notice: 'Job Queued.'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:is_scheduled, :query, object_rule_ids: [])
    end
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <h4>Primary Criteria</h4>
      <%= f.label :query %>
      <%= f.text_area :query, class: "radius" %>
    </div>
    <div class="field">
      <h4>Object Rules to Follow</h4>
      <%= f.select :object_rule_ids, ObjectRule.all.collect {|x| [x.extract_object + ' to ' + x.load_object, x.id]}, {}, :multiple => true, class: "radius" %>
    </div>
    <div>
      <h4>Scheduled</h4>
      <%= f.check_box :is_scheduled %>&nbsp;Run on Schedule
    </div>
    <div class="text-right">
      <%= f.submit "Save", class: "button radius"%>
    </div>
<% end %>

app/views/jobs/edit.html.erb
<div class="row">
	<div class="small-12 medium-6 columns">
		<div class="pan">
			<h1>Editing job</h1>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/jobs/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <div class="pan">
      <h1>Jobs <%= link_to 'New Etl job', new_job_path, class: 'right button inline radius' %></h1>
      <table>
        <thead>
          <tr>
            <th>Id</th>
            <th>Date/Time</th>
            <%
=begin %>
          <th>Extract Results</th>
          <th>Transform Results</th>
          <th>Successfully loaded?</th>
          <th>Errors</th>
          <th>Processing Time</th>
          <%
=end %>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @jobs.each do |job| %>
          <tr>
            <td><%= job.id %></td>
            <td><%= job.created_at.in_time_zone('America/Los_Angeles').strftime('%m/%d/%Y %l:%M%p') %></td>
            <%
=begin %>
            <td><%= job.extract_count %>(<%= link_to('Download', secure_get_path(job.id, 'extract'), {:target => '_blank'}) %>)</td>
            <td><%= job.transform_count %>(<%= link_to('Download', secure_get_path(job.id, 'transform'), {:target => '_blank'}) %>)</td>
            <td><%= job.load_count %>(<%= job.new_sf_users %> new)(<%= link_to('Download', secure_get_path(job.id, 'load'), {:target => '_blank'}) %>)</td>
            <td><%= job.errors_count %></td>
            <td><%= job.duration.round(2) %> seconds</td>
            <td><%= link_to "View Details", job_path(job.id) %></td>            
            <%
=end %>
              <td><%= link_to 'Show', job %></td>
              <td><%= link_to 'Edit', edit_job_path(job) %></td>
              <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="pan">
	<h1>New job</h1>

	<%= render 'form' %>

	<%= link_to 'Back', jobs_path %>
	
</div>

app/views/jobs/show.html.erb
<div class="row">
	<div class="small-12 columns">
	<div class="pan">
		<h1><%= @job.name || "Job" %><%= link_to 'Edit', edit_job_path(@job), class: "button inline radius right" %></h1>
		<div class="row">
			<div class="small-12 columns">
				<h5>Query</h5>
				 <p class="query"><%= @job.query %></p>
				 <div class="text-right">
				 <%= link_to "See Query Results", '/job/'+@job.id.to_s+'/count', remote: true, class: "button inline radius" %>
				 </div>
			</div>
		</div>
	</div>
	<hr />
	<div class="pan">
		<div class="row">
			<div class="small-12 columns">
				<h5>Etl Object Rules</h5>
				<table>
					<tr><th>Extract Object</th><th>Load Object</th></tr>
					<% @object_rules.each do |rule| %>
						<tr><td><%= rule.extract_object %></td><td><%= rule.load_object %></td></tr>
					<% end %>
				</table>
			</div>
		</div>
	</div>
	<hr />
	<div class="pan">
		<% @sub_job_groups.each do |job| %>
			<div class="row">
				<div class="small-12 columns">
					<h3><%= job.created_at.in_time_zone('America/Los_Angeles').strftime('%m/%d/%Y %l:%M%p') %><button class="button inline show radius right" data-job-group="<%= job.id %>" style="top:0px;">Show</button></h3>
					<table cellspacing="0" style="display:none;" data-job-group="<%= job.id %>">
						<tr>
							<th>Run at</th>
							<th>Extract Stage</th>
							<th>Transform Stage</th>
							<th>Load Stage</th>
							<th>Errors count</th>
						</tr>
							<% job.sub_jobs.each do |sub_job| %>
								<tr>
									<td><%= sub_job.created_at.in_time_zone('America/Los_Angeles').strftime('%m/%d/%Y %l:%M%p') %></td>
									<td><%= link_to("#{sub_job.extract_count} objects", secure_get_path(sub_job.id, 'extract'), {:target => '_blank'}) %></td>
									<td><%= link_to("Transform Results", secure_get_path(sub_job.id, 'transform'), {:target => '_blank'}) %></td>
									<td><%= link_to("#{sub_job.load_count} objects (#{sub_job.new_load_objects} new)", secure_get_path(sub_job.id, 'load'), {:target => '_blank'}) %></td>
									<td><%= sub_job.errors_count %></td>
								</tr>
							<% end %>
					</table>
				</div>
			</div>
		<% end %>
	</div>
			<script>
				$('button.show').click(function(){
					$('table[data-job-group=' + $(this).data('job-group') + ']').show()
				});
			</script>
			<div class="row">
				<div class="small-12 columns">
					<%= link_to "Run Job", '/job/'+@job.id.to_s+'/run', method: :post, class: "button radius right" %>
				</div>
			</div>
		</div>
	</div>
</div>