config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  get '/admins' => 'admins#index'
  get '/job/:id/count' => 'jobs#queryCount'
  post '/job/:id/run' => 'jobs#run'
  get '/download/:sub_job_id/:file_type', to: 'downloads#secureGet', as: 'secure_get'
  get '/visualizations/', to: 'visualizations#index', as: 'visualizations'
  post '/query/', to: 'visualizations#query', as: 'query'

  get '/feeds/actions/:id', to: 'feeds#actions', as: 'action_feed'

  root 'home#index'
  resources :jobs
  resources :object_rules do
    resources :field_rules
  end


  #DELAYEDJOBWEB
  authenticated :admin do
    mount DelayedJobWeb, :at => "/delayed_job"
  end
  #RAILS ADMIN
  mount RailsAdmin::Engine => '/admin/', as: 'rails_admin'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MagicAct</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400|Montserrat:700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
  <%= include_gon %>
</head>
<body>
	<div class="contain-to-grid">
		<nav class="top-bar" data-topbar role="navigation">
		  <ul class="title-area">
		    <li class="name">
		      <h1><%= link_to root_url do %>MagicAct<% end %></h1>
		    </li>
		     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
		    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
		  </ul>

		  <section class="top-bar-section">
		    <!-- Left Nav Section -->
		    <!--<ul class="left">
				<li class="has-dropdown">
					<a href="#">Right Button Dropdown</a>
					<ul class="dropdown">
						<li><a href="#">First link in dropdown</a></li>
						<li class=""><a href="#">Active link in dropdown</a></li>
					</ul>
				</li>
		    </ul>-->
		    <ul class="right">
		    	<li class="<%=  "active" if controller_name == 'home'%>"><%= link_to "Dashboard", root_url %></li>

				<li class="<%#  "active" if controller_name == 'home'%>"><%= link_to "Visualizations", visualizations_url %></li>
		    	<li class="<%#  "active" if controller_name == 'home'%>"><%= link_to "Stripe Donations", root_url %></li>
				<li class="has-dropdown">
					<a href="#">ETL Jobs</a>
					<ul class="dropdown">
						<li class="<%=  "active" if controller_name == 'jobs'%>"><%= link_to "Run Jobs", jobs_url %></li>
						<li class="<%=  "active" if controller_name == 'object_rules'%>"><%= link_to "Object Rules", object_rules_url %></li>
						<li><%= link_to "Delayed Job", delayed_job_web_url %></li>
					</ul>
				</li>
		    </ul>
		  </section>
		</nav>
	</div>
	<div class="application container">
		<% unless notice.nil? %>
			<div data-alert class="alert-box radius">
				<%= notice %>
				<a href="#" class="close">&times;</a>
			</div>
		<% end %>
		<%= yield %>
	</div>
	<div id="footer">
		<div class="container">
			Proudly Crafted by <a href="http://jcmorrow.com" target="_blank">@jcmorrow</a>
		</div>
	</div>
</body>
</html>