config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  get '/admins' => 'admins#index'
  get '/job/:id/count' => 'jobs#queryCount'
  post '/job/:id/run' => 'jobs#run'
  get '/download/:sub_job_id/:file_type', to: 'downloads#secureGet', as: 'secure_get'
  get '/visualizations/', to: 'visualizations#index', as: 'visualizations'
  post '/query/', to: 'visualizations#query', as: 'query'

  get '/feeds/actions/:id', to: 'feeds#actions', as: 'action_feed'

  root 'home#index'
  resources :jobs
  resources :object_rules do
    resources :field_rules
  end


  #DELAYEDJOBWEB
  authenticated :admin do
    mount DelayedJobWeb, :at => "/delayed_job"
  end
  #RAILS ADMIN
  mount RailsAdmin::Engine => '/admin/', as: 'rails_admin'

end

app/models/object_rule.rb
class ObjectRule < ActiveRecord::Base
	has_many :field_rules
	has_many :job_object_rels
	has_many :jobs, :through => :job_object_rels

	def composeSelect
		select = 'SELECT '
		comma = false
		field_rules.each do |field_rule|
			comma ? select += ', ' : comma = true
			select += field_rule.extract_field + ' as ' + field_rule.load_field
		end
		if(!self.custom_from_clause.nil? && self.custom_from_clause != '')
			select += ' '<<self.custom_from_clause
		else	
			select += ' FROM ' + extract_object
		end
		return select
	end
end

app/controllers/object_rules_controller.rb
class ObjectRulesController < ApplicationController
  before_action :set_object_rule, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  require 'action_kit_api'

  # GET /object_rules
  # GET /object_rules.json
  def index
    @object_rules = ObjectRule.includes(:field_rules).all
  end

  # GET /object_rules/1
  # GET /object_rules/1.json
  def show
    @object_rule = ObjectRule.includes(:field_rules).find(params[:id])
    salesforce = Restforce.new
    actionkit = ActionKitApi.new
    
    @actionKitFields = []
    @salesForceFields = []
    actionkit.query("SELECT DISTINCT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = '#{@object_rule.extract_object}'").each do |field|
      @actionKitFields.push(field[0])
    end
    salesforce.describe(@object_rule.load_object)[:fields].each do |field|
      @salesForceFields.push(field[:name])
    end
    gon.push(:actionKitFields => @actionKitFields,
             :salesForceFields => @salesForceFields)
  end

  # GET /object_rules/new
  def new
    @object_rule = ObjectRule.new

    salesforce = Restforce.new
    actionkit = ActionKitApi.new

    @object_rules = ObjectRule.all
    actionKitTables = []
    salesForceObjects = []
    actionkit.query("SELECT TABLE_NAME FROM information_schema.tables WHERE table_name LIKE 'core%'").each do |table|
      actionKitTables.push(table[0])
    end
    salesforce.describe.each do |object|
      salesForceObjects.push(object[:name])
    end
    gon.push(:actionKitTables => actionKitTables,
             :salesForceObjects => salesForceObjects)
  end

  # GET /object_rules/1/edit
  def edit
  end

  # POST /object_rules
  # POST /object_rules.json
  def create
    @object_rule = ObjectRule.new(object_rule_params)

    respond_to do |format|
      if @object_rule.save
        format.html { redirect_to object_rule_field_rules_path(@object_rule, notice: ' object rule was successfully created.') }
        format.json { render :show, status: :created, location: @object_rule }
      else
        format.html { render :new }
        format.json { render json: @object_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /object_rules/1
  # PATCH/PUT /object_rules/1.json
  def update
    respond_to do |format|
      if @object_rule.update(object_rule_params)
        format.html { redirect_to @object_rule, notice: ' object rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @object_rule }
      else
        format.html { render :edit }
        format.json { render json: @object_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /object_rules/1
  # DELETE /object_rules/1.json
  def destroy
    @object_rule.destroy
    respond_to do |format|
      format.html { redirect_to object_rules_url, notice: ' object rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #VISUALIZER

  def explore
    salesforce = Restforce.new
    actionkit = ActionKitApi.new
    @object_rules = ObjectRule.all
    actionKitTables = []
    salesForceObjects = []
    actionkit.query("SELECT TABLE_NAME FROM information_schema.tables WHERE table_name LIKE 'core%'").each do |table|
      actionKitTables.push(table[0])
    end
    salesforce.describe.each do |object|
      salesForceObjects.push(object[:name])
    end
    gon.push(:actionKitTables => actionKitTables,
             :salesForceObjects => salesForceObjects)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_object_rule
      @object_rule = ObjectRule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def object_rule_params
      params.require(:object_rule).permit(:load_object, :extract_object, :active, :is_primary, :custom_from_clause)
    end
end

app/views/object_rules/_form.html.erb
<%= form_for(@object_rule) do |f| %>
  <% if @object_rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@object_rule.errors.count, "error") %> prohibited this object_rule from being saved:</h2>

      <ul>
      <% @object_rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :extract_object, "ActionKit Table" %>
    <%= f.text_field :extract_object, class: "radius" %>
  </div>
  <div class="field">
    <%= f.label :load_object, "SalesForce Object" %>
    <%= f.text_field :load_object, class: "radius" %>
  </div>
  <div class="field">
      <%= f.label :custom_from_clause %>
      <%= f.text_area :custom_from_clause, class: "radius" %>
    </div>
  <input type="hidden" value="true" />
  <div class="actions">
    <%= f.submit "Save", class: "radius button" %>
  </div>
<% end %>

<script type="text/javascript">

  var substringMatcher = function(strs) {
    return function findMatches(q, cb) {
      var matches, substrRegex;
   
      // an array that will be populated with substring matches
      matches = [];
   
      // regex used to determine if a string contains the substring `q`
      substrRegex = new RegExp(q, 'i');
   
      // iterate through the pool of strings and for any string that
      // contains the substring `q`, add it to the `matches` array
      $.each(strs, function(i, str) {
        if (substrRegex.test(str)) {
          // the typeahead jQuery plugin expects suggestions to a
          // JavaScript object, refer to typeahead docs for more info
          matches.push({ value: str });
        }
      });
   
      cb(matches);
    };
  };


  $('#object_rule_extract_object').typeahead({
    hint: true,
    highlight: true,
    minLength: 1
  },
  {
    name: 'ActionKitTables',
    displayKey: 'value',
    source: substringMatcher(gon.actionKitTables)
  });
  $('#object_rule_load_object').typeahead({
    hint: true,
    highlight: true,
    minLength: 1
  },
  {
    name: 'SalesForceObjects',
    displayKey: 'value',
    source: substringMatcher(gon.salesForceObjects)
  });
</script>

app/views/object_rules/edit.html.erb
<div class="row">
	<div class="small-12 medium-6 columns">
		<div class="pan">
			<h1>Edit Object Rule</h1>
			<%= render 'form' %>
		</div>
	</div>
	<div class="small-12 medium-6 columns">
		<div class="dark help">
			<h4>Help</h4>
			<p><strong>ActionKit Table</strong>: A table name (example: core_user, core_mailing, etc.)</p>
			<p><strong>SalesForce Object</strong>: A SalesForce object name (example: Account, Contact, Akid__c, etc.)</p>
			<p><strong>Custom From Clause</strong>: If you will be pulling fields from multiple ActionKit tables this should include a join statement which joins all the tables (example: FROM core_user JOIN core_action ON core_action.user_id = core_user.id)</p>
		</div>
	</div>
</div>

app/views/object_rules/explore.html.erb
</div>
	<div class="visualizer row" style="min-height:500px;max-width:none;">
		<div class="small-12 columns">
			<div class="pan">
				<h3 class="text-center">Object Rules</h3>
				<table cellspacing="0">
					<tr><th class="text-center">ActionKit</th><th class="text-center">SalesForce</th><th></th></tr>
					<% @object_rules.each do |rule| %>
						<tr>
							<td><input type="text" class="radius" value="<%= rule.extract_object %>" readonly /></td>
							<td><input type="text" class="radius" value="<%= rule.load_object %>" readonly /></td>
							<td><button class="button inline radius">Fields</button></td>
						</tr>
					<% end %>
						<tr>
							<td><input id="extract-input" type="text" class="radius typeahead" /></td>
							<td><input id="load-input" type="text" class="radius" /></td>
							<td><button class="button inline radius">Save</button></td>
						</tr>
					</table>
				<button id="new-rule" class="button radius">New Object Rule</button><button class="button radius">Edit Object Rules</button>
			</div>
		</div>
	</div>
<div class="application container">
<!--
Begin loading stuff asynchronously
-->
<script type="text/javascript">

	$('#new-button').click(function(){

	});


	var substringMatcher = function(strs) {
	  return function findMatches(q, cb) {
	    var matches, substrRegex;
	 
	    // an array that will be populated with substring matches
	    matches = [];
	 
	    // regex used to determine if a string contains the substring `q`
	    substrRegex = new RegExp(q, 'i');
	 
	    // iterate through the pool of strings and for any string that
	    // contains the substring `q`, add it to the `matches` array
	    $.each(strs, function(i, str) {
	      if (substrRegex.test(str)) {
	        // the typeahead jQuery plugin expects suggestions to a
	        // JavaScript object, refer to typeahead docs for more info
	        matches.push({ value: str });
	      }
	    });
	 
	    cb(matches);
	  };
	};


	$('#extract-input').typeahead({
	  hint: true,
	  highlight: true,
	  minLength: 1
	},
	{
	  name: 'ActionKitTables',
	  displayKey: 'value',
	  source: substringMatcher(gon.actionKitTables)
	});
	$('#load-input').typeahead({
	  hint: true,
	  highlight: true,
	  minLength: 1
	},
	{
	  name: 'SalesForceObjects',
	  displayKey: 'value',
	  source: substringMatcher(gon.salesForceObjects)
	});


</script>

app/views/object_rules/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2 class="text-center">Object Rules</h2>
    <% @object_rules.each do |rule| %>
    <div class="row">
      <div class="small-12 columns">
        <div class="pan">
        <h3><%= rule.extract_object %> to <%= rule.load_object %><%= link_to  "Edit Rule", object_rule_path(id: rule.id), class: 'button inline radius right' %></h3>
          <hr />
          <div class="small-6 columns">
            Active:&nbsp;<%= raw('<i class="fa fa-check"></i>') if rule.active %>
          </div>
          <div class="small-6 columns">
            Is Primary:&nbsp;<%= raw('<i class="fa fa-check"></i>') if rule.is_primary %>
          </div>
          <hr />
          <h4>Field Rules</h4>
          <table cellspacing="0">
            <tr><th>Extract Field</th><th>Transformation</th><th>Load Field</th><th>Active?</th><th></th></tr>
            <% rule.field_rules.each do |field_rule| %>
            <tr class="nested"><td width="200"><%= field_rule.extract_field %></td><td width="200"><%= field_rule.transformation %></td><td width="200"><%= field_rule.load_field %></td><td width="50"><%= field_rule.active %></td><td width="50"><%= field_rule.is_primary %><td width="50"><%= field_rule.is_foreign_key %></td></td></tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
    <% end %>
    <div class="row">
      <div class="small-12 columns text-right">
        <button class="button radius">Edit Object Rules</button>
        <%= link_to  "New Object Rule", new_object_rule_url, class: 'button radius' %>
      </div>
    </div>
  </div>
</div>
</div>

<style>
  table
  {
    border-color: #ccc;
  }
  td
  {
    border-bottom: 1px solid;
    border-color: inherit;
  }
  th
  {
    border-bottom: 1px solid;
    border-color: #999;
  }
</style>

app/views/object_rules/new.html.erb
<div class="row">
	<div class="small-12 medium-6 columns">
		<div class="pan">
			<h3>New Object Rule</h3>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/object_rules/show.html.erb
<div class="row">
	<div class="small-12 columns">
		<div class="pan">
			<h3><%= @object_rule.extract_object %> to <%= @object_rule.load_object %></h3>
			<p>
			  <strong>Extract Object:</strong>
			  <%= @object_rule.extract_object %>
			</p>
			<p>
			  <strong>Load Object:</strong>
			  <%= @object_rule.load_object %>
			</p>
			<p>
			  <strong>Active:</strong>
			  <%= @object_rule.active %>
			</p>
			<p>
			  <strong>Is Primary:</strong>
			  <%= @object_rule.is_primary %>
			</p>
      <p>
        Custom From Clause:
        <%= @object_rule.custom_from_clause %>
      </p>
			<%= link_to 'Edit', edit_object_rule_path(@object_rule) %> |
			<%= link_to 'Back', object_rules_path %>
		</div>
	</div>
</div>
<div class="row">
  <div class="small-12 columns">
    <div class="pan">
    	<h3>Field Rules <%= link_to 'New field rule', new_object_rule_field_rule_path(:object_rule_id => @object_rule.id), class: 'right button inline radius' %></h3>
      <table>
        <thead>
          <tr>
            <th width="200">Extract field</th>
            <th width="200">Transformation</th>
            <th width="200">Load field</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @object_rule.field_rules.each do |field_rule| %>
            <tr>
              <td width="200"><%= field_rule.extract_field %></td>
              <td width="200"><%= field_rule.transformation %></td>
              <td width="200"><%= field_rule.load_field %></td>
              <td width="50"><%= link_to "Edit", edit_object_rule_field_rule_path(@object_rule, field_rule) %></td>
              <td width="50"><%= link_to "Delete", object_rule_field_rule_path(@object_rule, field_rule),
            :confirm => 'Are you sure?', :method => :delete %></td>
            </tr>
          <% end %>
<%
=begin %>

            <%= form_tag("/object_rules/#{@object_rule.id}/field_rules", method:"POST") do %>
              <tr>
                <td width="200"><input id="field_rule_extract_field" class="radius" type="text" name="field_rule[extract_field]" /></td>
                <td width="200"><input id="field_rule_transformation" class="radius" type="text" name="field_rule[transformation]" /></td>
                <td width="200"><input id="field_rule_load_field" class="radius" type="text" name="field_rule[load_field]" /></td>
              </tr>
              <tr>
                <td class="text-right" colspan="3"><button type="submit" class="button radius">Save</button></td>
              </tr>
            <% end %>
<%
=end %>
        </tbody>
      </table>
      <div class="bank row">
        <div class="small-12 medium-6 columns">
          <% @actionKitFields.each do |field| %>
          <span class="ak-label">
            <%= field %>
          </span>
          <% end %>
        </div>
        <div class="small-12 medium-6 columns">
          <% @salesForceFields.each do |field| %>
          <span class="sf-label">
            <%= field %>
          </span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">

  var substringMatcher = function(strs) {
    return function findMatches(q, cb) {
      var matches, substrRegex;
   
      // an array that will be populated with substring matches
      matches = [];
   
      // regex used to determine if a string contains the substring `q`
      substrRegex = new RegExp(q, 'i');
   
      // iterate through the pool of strings and for any string that
      // contains the substring `q`, add it to the `matches` array
      $.each(strs, function(i, str) {
        if (substrRegex.test(str)) {
          // the typeahead jQuery plugin expects suggestions to a
          // JavaScript object, refer to typeahead docs for more info
          matches.push({ value: str });
        }
      });
   
      cb(matches);
    };
  };


  $('#field_rule_extract_field').typeahead({
    hint: true,
    highlight: true,
    minLength: 1
  },
  {
    name: 'ActionKitFields',
    displayKey: 'value',
    source: substringMatcher(gon.actionKitFields)
  });
  $('#field_rule_load_field').typeahead({
    hint: true,
    highlight: true,
    minLength: 1
  },
  {
    name: 'SalesForceFields',
    displayKey: 'value',
    source: substringMatcher(gon.salesForceFields)
  });
</script>